import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Page } from "../../components";

const ListingDetails: NextPage = () => {
  return (
    <Page>
      <Head>
        <title>Kasuwa Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Se Za Kasuwa</h1>
    </Page>
  );
};

export default ListingDetails;
